import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
Next Up — Obsidian plugin. Source: https://github.com/<your-org>/next-up
This file is generated by esbuild; edit src/ instead.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

/* The headless CLI (same core, over a vault on disk) bundles to kb.js for cron jobs. */
const cli = await esbuild.context({
  banner: { js: "#!/usr/bin/env node\n" + banner },
  entryPoints: ["src/kb/cli.ts"],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  external: [...builtins],
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "kb.js",
  minify: false,
});

if (prod) {
  await context.rebuild();
  await cli.rebuild();
  process.exit(0);
} else {
  await context.watch();
  await cli.watch();
}
